
package cafeotomasyonuprojesı;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Casper
 */
public class anamenu extends javax.swing.JFrame {

    /**
     * Creates new form anamenu
     */
    public anamenu() {
        initComponents();
           SimpleDateFormat bicim=new SimpleDateFormat("dd/M/yyyy");
Date tarih=new Date();

lbl_tarıh2.setText((bicim.format(tarih)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_yonetım = new javax.swing.JButton();
        btn_masalar = new javax.swing.JButton();
        btn_gunıslemlerı = new javax.swing.JButton();
        btn_urunler = new javax.swing.JButton();
        lbl_tarıh2 = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_yonetım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/Yönetim.jpg"))); // NOI18N
        btn_yonetım.setText("jButton1");
        btn_yonetım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yonetımActionPerformed(evt);
            }
        });
        getContentPane().add(btn_yonetım, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 670, 390, 205));

        btn_masalar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/masalar.jpg"))); // NOI18N
        btn_masalar.setText("jButton1");
        btn_masalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masalarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 390, 205));

        btn_gunıslemlerı.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/Gün işlemleri.jpg"))); // NOI18N
        btn_gunıslemlerı.setText("jButton1");
        btn_gunıslemlerı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gunıslemlerıActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gunıslemlerı, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 390, 205));

        btn_urunler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/Ürünler1.jpg"))); // NOI18N
        btn_urunler.setText("jButton1");
        btn_urunler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunlerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_urunler, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 170, 380, 205));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 430, 60));

        arkaplan.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masalarActionPerformed
      masalar masalarıac=new masalar();
      masalarıac.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btn_masalarActionPerformed

    private void btn_urunlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunlerActionPerformed
     ürünler nesne=new ürünler();
     nesne.setVisible(true);
     nesne.say();
     this.dispose();
      
    }//GEN-LAST:event_btn_urunlerActionPerformed

    private void btn_gunıslemlerıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gunıslemlerıActionPerformed
       günislemleri gunac=new günislemleri();
       gunac.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_gunıslemlerıActionPerformed

    private void btn_yonetımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yonetımActionPerformed
        yönetim yonetımıac =new yönetim();
        yonetımıac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_yonetımActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anamenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton btn_gunıslemlerı;
    private javax.swing.JButton btn_masalar;
    private javax.swing.JButton btn_urunler;
    private javax.swing.JButton btn_yonetım;
    private javax.swing.JLabel lbl_tarıh2;
    // End of variables declaration//GEN-END:variables
}
