/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeotomasyonuprojesı;

import com.toedter.calendar.JDayChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casper
 */
public class günislemleri extends javax.swing.JFrame {

    /**
     * Creates new form günislemleri
     */
    public günislemleri() {
        initComponents();
        SimpleDateFormat bicim = new SimpleDateFormat("dd/M/yyyy");
        Date tarih = new Date();

        lbl_tarıh2.setText((bicim.format(tarih)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_raporlar = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lbl_deneme = new javax.swing.JLabel();
        datechooser = new datechooser.beans.DateChooserPanel();
        lbl_tarıh2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kazanc = new javax.swing.JLabel();
        lbl_secılentarıh = new javax.swing.JLabel();
        lbl_tarıh = new javax.swing.JLabel();
        lbl_musterısayısıyaz = new javax.swing.JLabel();
        ziyaretcisayisi = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_raporlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RAPORNO", "TUTAR", "MASA", "TARİH", "SAAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_raporlar);
        if (tbl_raporlar.getColumnModel().getColumnCount() > 0) {
            tbl_raporlar.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, 597, 317));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/ev.png"))); // NOI18N
        jButton7.setText(" ANAMENU");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 378, -1, 43));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/gozat.png"))); // NOI18N
        jButton8.setText("  GERİ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 149, -1));

        lbl_deneme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lbl_deneme, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 473, 1128, 29));

        datechooser.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                datechooserOnSelectionChange(evt);
            }
        });
        getContentPane().add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 118, 433, 242));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, 430, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GÜNLÜK   KAZANÇ :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 240, 170, 40));

        lbl_kazanc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_kazanc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kazanc.setText("jLabel2");
        getContentPane().add(lbl_kazanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 250, 170, 20));

        lbl_secılentarıh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_secılentarıh.setForeground(new java.awt.Color(255, 255, 255));
        lbl_secılentarıh.setText("SEÇTİĞİNİZ TARİH :");
        getContentPane().add(lbl_secılentarıh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 200, -1, -1));

        lbl_tarıh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_tarıh.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh.setText("jLabel2");
        getContentPane().add(lbl_tarıh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 200, 210, -1));

        lbl_musterısayısıyaz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_musterısayısıyaz.setForeground(new java.awt.Color(255, 255, 255));
        lbl_musterısayısıyaz.setText("ZİYARETÇİ SAYISI :");
        getContentPane().add(lbl_musterısayısıyaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 300, -1, -1));

        ziyaretcisayisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ziyaretcisayisi.setForeground(new java.awt.Color(255, 255, 255));
        ziyaretcisayisi.setText("jLabel2");
        getContentPane().add(ziyaretcisayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 300, 170, -1));

        arkaplan.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        anamenu nesne = new anamenu();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        anamenu nesne = new anamenu();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void datechooserOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_datechooserOnSelectionChange
        String str = "" + datechooser.getSelectedDate();

        int yıl = str.indexOf("YEAR=");
        int virgül = str.indexOf(",", yıl);
        String deneyıl = str.substring(yıl + 5, virgül);
        System.out.println(""+str);
        int gun = str.indexOf("DAY_OF_MONTH=");
        int virgülgun = str.indexOf(",", gun);
        String denegun = str.substring(gun + 13, virgülgun);

        int ay = str.indexOf("MONTH=");
        int virgülay = str.indexOf(",", ay);
        String deneay = str.substring(ay + 6, virgülay);
        int ayguncel = Integer.parseInt(deneay);
        int ayson = ayguncel + 1;

        String birlestir = denegun + "/" + ayson + "/" + deneyıl;
        lbl_deneme.setText(birlestir);

        DefaultTableModel dtm;
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"RID", "UTUTAR", "MASAID", "RTARIH", "RSAAT"});
        tbl_raporlar.setModel(dtm);
        dtm.setRowCount(0);
        double kazanc=0;
        int say=0;
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
               
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.RAPORLAR WHERE RTARIH='" + birlestir + "'");
                lbl_tarıh.setText(birlestir);
                while (rs.next()) {
                   
                    int raporıd = rs.getInt("RID");
                    double raportutar = rs.getDouble("RTUTAR");
                    kazanc=kazanc+raportutar;
                    
                    say++;
                   
                    int masaıd = rs.getInt("MASAID");
                    String tarıh = rs.getString("RTARIH");
                    String saat = rs.getString("RSAAT");

                    dtm.addRow(new Object[]{raporıd, raportutar, masaıd, tarıh, saat});

                }
                lbl_kazanc.setText(kazanc +" ₺");
               ziyaretcisayisi.setText(say +" KİŞİ");
                con.close();
       
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_datechooserOnSelectionChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(günislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(günislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(günislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(günislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new günislemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private datechooser.beans.DateChooserPanel datechooser;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_deneme;
    private javax.swing.JLabel lbl_kazanc;
    private javax.swing.JLabel lbl_musterısayısıyaz;
    private javax.swing.JLabel lbl_secılentarıh;
    private javax.swing.JLabel lbl_tarıh;
    private javax.swing.JLabel lbl_tarıh2;
    private javax.swing.JTable tbl_raporlar;
    private javax.swing.JLabel ziyaretcisayisi;
    // End of variables declaration//GEN-END:variables
}
