/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeotomasyonuprojesı;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casper
 */
public class personelekle extends javax.swing.JFrame {

    DefaultTableModel dtm;

    public personelekle() {
        initComponents();
        SimpleDateFormat bicim = new SimpleDateFormat("dd/M/yyyy");
        Date tarih = new Date();
        lbl_tarıh2.setText((bicim.format(tarih)));
      
        try {
             
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"PID", "PISIM", "PSOYISIM", "PTEL", "PMAAS", "PGOREV","PTCKN"});
        jTable1.setModel(dtm);
         dtm.setRowCount(0);
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.PERSONEL ");
                while (rs.next()) {
                    int personelıd = rs.getInt("PID");
                    String personelısım = rs.getString("PISIM");
                    String personelsoyısım = rs.getString("PSOYISIM");
                    int personeltelefon = rs.getInt("PTEL");
                    double personelmaas = rs.getDouble("PMAAS");
                    String personelgorev = rs.getString("PGOREV");
                    int personeltckn = rs.getInt("PTCKN");
                    dtm.addRow(new Object[]{personelıd, personelısım, personelsoyısım, personeltelefon, personelmaas, personelgorev, personeltckn});

                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_personelıd = new javax.swing.JTextField();
        txt_personeladı = new javax.swing.JTextField();
        txt_personelsoyad = new javax.swing.JTextField();
        txt_personeltelefon = new javax.swing.JTextField();
        txt_personelmaas = new javax.swing.JTextField();
        txt_personelgorev = new javax.swing.JTextField();
        txt_personeltckn = new javax.swing.JTextField();
        btn_anamenu = new javax.swing.JButton();
        btn_gerı = new javax.swing.JButton();
        btn_ekle = new javax.swing.JButton();
        bnt_duzenle = new javax.swing.JButton();
        lbl_tarıh2 = new javax.swing.JLabel();
        tbl_personeller = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PERSONEL ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 62, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERSENEL ADI :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 124, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PERSONEL TELEFON :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PERSONEL TCKN :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PERSONEL GÖREVİ :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 348, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PERSONEL SOYİSİM :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERSONEL MAAS :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 296, -1, -1));

        txt_personelıd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personelıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 62, 172, 37));

        txt_personeladı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personeladı, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 117, 172, 37));

        txt_personelsoyad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personelsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 173, 172, 37));

        txt_personeltelefon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personeltelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 233, 172, 37));

        txt_personelmaas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personelmaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 289, 172, 37));

        txt_personelgorev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personelgorev, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 341, 172, 37));

        txt_personeltckn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personeltckn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 393, 172, 37));

        btn_anamenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_anamenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/ev.png"))); // NOI18N
        btn_anamenu.setText(" ANAMENU");
        btn_anamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anamenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 461, -1, -1));

        btn_gerı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gerı.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/gozat.png"))); // NOI18N
        btn_gerı.setText("  GERİ");
        btn_gerı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerıActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gerı, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 149, -1));

        btn_ekle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/personel_ekle.png"))); // NOI18N
        btn_ekle.setText(" EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 457, 140, 41));

        bnt_duzenle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_duzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/personel_duzenle.png"))); // NOI18N
        bnt_duzenle.setText(" DÜZENLE");
        bnt_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_duzenleActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_duzenle, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 520, -1, -1));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, 430, 60));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PERSONEL ID", "İSİM", "SOYİSİM", "TELEFON", "MAAŞ", "T.C. NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_personeller.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(tbl_personeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 940, 370));

        arkaplan.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        if (txt_personelıd.getText().isEmpty() && txt_personeladı.getText().isEmpty() && txt_personelmaas.getText().isEmpty()
                && txt_personeltckn.getText().isEmpty() && txt_personeltelefon.getText().isEmpty() && txt_personelsoyad.getText().isEmpty() && txt_personelgorev.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "lütfen tüm bilgileri doldurunuz.");
            return;
        }
        String gelenkullanıcıadı = txt_personelıd.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM SA.PERSONEL WHERE PID=" + gelenkullanıcıadı);
            if (rs.next()) {
                

                JOptionPane.showMessageDialog(rootPane, "AYNI İD İLE BİRDEN FAZLA PERSONEL KAYIT EDİLEMEZ.");
                txt_personelıd.setText("");
            } else {
                String insert = "INSERT INTO SA.PERSONEL (PID,PISIM,PSOYISIM,PTEL,PGOREV,PTCKN) VALUES ("
                        + txt_personelıd.getText() + ",'" + txt_personeladı.getText().trim()
                        + "','" + txt_personelsoyad.getText().trim() + "',"
                        + txt_personeltelefon.getText().trim() + ",'" + txt_personelgorev.getText().trim() + "'," + txt_personeltckn.getText().trim()
                        + ")";
                System.out.println("" + insert);
                stmt.executeUpdate(insert);
             

               personelekle nesne = new personelekle();
                    nesne.setVisible(true);
                    dispose();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }


    }//GEN-LAST:event_btn_ekleActionPerformed

    private void bnt_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_duzenleActionPerformed
        if (txt_personelıd.getText().isEmpty() && txt_personeladı.getText().isEmpty() && txt_personelmaas.getText().isEmpty()
                && txt_personeltckn.getText().isEmpty() && txt_personeltelefon.getText().isEmpty() && txt_personelsoyad.getText().isEmpty() && txt_personelgorev.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "lütfen tüm bilgileri doldurunuz.");
            return;
        }
        String gelenkullanıcıadı = txt_personelıd.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM SA.PERSONEL WHERE PID=" + gelenkullanıcıadı);
            if (rs.next()) {
                String update = "UPDATE SA.PERSONEL SET PID=" + txt_personelıd.getText().trim()
                        + ",PISIM='" + txt_personeladı.getText().trim()
                        + "',PSOYISIM='" + txt_personelsoyad.getText().trim() + "',PMAAS=" + txt_personelmaas.getText().trim() + ",PGOREV='" + txt_personelgorev.getText().trim() + "'"
                        + " WHERE PID=" + txt_personelıd.getText().trim();
                System.out.println("" + update);
                stmt.executeUpdate(update);
                txt_personelıd.setText("");
                txt_personeladı.setText("");
                txt_personelsoyad.setText("");
                txt_personeltelefon.setText("");
                txt_personelgorev.setText("");
                txt_personeltckn.setText("");

                JOptionPane.showMessageDialog(rootPane, "Personel bilgileri güncellendi.");
            } else {

                JOptionPane.showMessageDialog(rootPane, "Personel bulunamadı.");
                txt_personelıd.setText("");
                txt_personeladı.setText("");
                txt_personelsoyad.setText("");
                txt_personeltelefon.setText("");
                txt_personelgorev.setText("");
                txt_personeltckn.setText("");
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }

    }//GEN-LAST:event_bnt_duzenleActionPerformed

    private void btn_anamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anamenuActionPerformed
        anamenu nesne = new anamenu();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_anamenuActionPerformed

    private void btn_gerıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerıActionPerformed
        yönetim nesne = new yönetim();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_gerıActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton bnt_duzenle;
    private javax.swing.JButton btn_anamenu;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_gerı;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_tarıh2;
    private javax.swing.JScrollPane tbl_personeller;
    private javax.swing.JTextField txt_personeladı;
    private javax.swing.JTextField txt_personelgorev;
    private javax.swing.JTextField txt_personelmaas;
    private javax.swing.JTextField txt_personelsoyad;
    private javax.swing.JTextField txt_personeltckn;
    private javax.swing.JTextField txt_personeltelefon;
    private javax.swing.JTextField txt_personelıd;
    // End of variables declaration//GEN-END:variables
}
