/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeotomasyonuprojesı;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casper
 */
public class personelsıl extends javax.swing.JFrame {

    /**
     * Creates new form personelsıl
     */
    DefaultTableModel dtm;

    public personelsıl() {
        initComponents();
        SimpleDateFormat bicim = new SimpleDateFormat("dd/M/yyyy");
        Date tarih = new Date();
        lbl_tarıh2.setText((bicim.format(tarih)));
        try {

            dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new Object[]{"PID", "PISIM", "PSOYISIM", "PTEL", "PMAAS", "PGOREV", "PTCKN"});
            jTable1.setModel(dtm);
            dtm.setRowCount(0);
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.PERSONEL ");
                while (rs.next()) {
                    int personelıd = rs.getInt("PID");
                    String personelısım = rs.getString("PISIM");
                    String personelsoyısım = rs.getString("PSOYISIM");
                    int personeltelefon = rs.getInt("PTEL");
                    double personelmaas = rs.getDouble("PMAAS");
                    String personelgorev = rs.getString("PGOREV");
                    int personeltckn = rs.getInt("PTCKN");
                    dtm.addRow(new Object[]{personelıd, personelısım, personelsoyısım, personeltelefon, personelmaas, personelgorev, personeltckn});

                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_personelıd = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_tarıh2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_ıd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ısım = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_fıyat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_kategorıadı = new javax.swing.JLabel();
        tbl_personeller = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        arkaplan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERSONEL ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 100, -1, -1));

        txt_personelıd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_personelıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 100, 148, 22));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/ev.png"))); // NOI18N
        jButton8.setText(" ANAMENU");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 177, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/gozat.png"))); // NOI18N
        jButton9.setText("  GERİ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 228, 149, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/personel_sil.png"))); // NOI18N
        jButton2.setText(" SİL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 177, 113, -1));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 60, 430, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SİLDİĞİNİZ PERSONELİN ;");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        lbl_ıd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ıd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_ıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("İSMİ :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        lbl_ısım.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ısım.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_ısım, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SOYİSİM :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        lbl_fıyat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_fıyat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_fıyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GÖREVİ :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        lbl_kategorıadı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_kategorıadı.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_kategorıadı, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 190, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PERSONEL ID", "İSİM", "SOYİSİM", "TELEFON", "MAAŞ", "T.C. NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_personeller.setViewportView(jTable1);

        getContentPane().add(tbl_personeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 890, 370));

        arkaplan1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan1.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1920, 1100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_personelıd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "lütfen personel ıd numarası giriniz.");
            return;
        } else {
            String gelenkullanıcı = txt_personelıd.getText();
            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc", "sa", "as");
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.PERSONEL WHERE PID=" + gelenkullanıcı);

                if (rs.next()) {

                    int ıd = rs.getInt("PID");
                    lbl_ıd.setText("" + ıd);
                    String isim = rs.getString("PISIM");
                    lbl_ısım.setText(isim);
                    String psoyısım = rs.getString("PSOYISIM");
                    lbl_fıyat.setText(psoyısım);
                    String kategoriadi = rs.getString("PGOREV");
                    lbl_kategorıadı.setText(kategoriadi);
                    String delete = "DELETE FROM SA.PERSONEL WHERE PID=" + gelenkullanıcı;
                    System.out.println(delete);
                    stmt.executeUpdate(delete);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "kullanıcı bulunamadı.");
                    txt_personelıd.setText("");
                }
                con.close();
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        anamenu nesne = new anamenu();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        yönetim nesne = new yönetim();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelsıl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelsıl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelsıl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelsıl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelsıl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_fıyat;
    private javax.swing.JLabel lbl_kategorıadı;
    private javax.swing.JLabel lbl_tarıh2;
    private javax.swing.JLabel lbl_ıd;
    private javax.swing.JLabel lbl_ısım;
    private javax.swing.JScrollPane tbl_personeller;
    private javax.swing.JTextField txt_personelıd;
    // End of variables declaration//GEN-END:variables
}
