package cafeotomasyonuprojesı;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;

import static java.time.LocalDate.now;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;

import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static jdk.nashorn.internal.runtime.regexp.joni.Syntax.Java;

public class satıs extends javax.swing.JFrame {

    String sepet = "";
    DefaultTableModel dtm;
    double topla = 0;
    int masaıd;

    public satıs(int masaid) {

        initComponents();
           SimpleDateFormat bicim=new SimpleDateFormat("dd/M/yyyy");
Date tarih=new Date();

lbl_tarıh2.setText((bicim.format(tarih)));
        masaıd = masaid;
        //  System.out.println("satısın metodun içindeki masa id :"+masaid);
        lbl_masaıd.setText(masaıd + "");
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"UID", "UISIM", "UFIAT", "UVERGIORAN", "UKATEGORI", "UKATEGORIID"});
        tbl_urunler.setModel(dtm);
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.KATEGORILER ");
                while (rs.next()) {
                    int kategorııd = rs.getInt("UKATEGORIID");
                    String kategorıadı = rs.getString("UKATEGORI");
                    cmb_kategorıler.addItem(kategorıadı);
                   
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_kategorıler = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_urunler = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_urunıd = new javax.swing.JTextField();
        btn_satıs = new javax.swing.JButton();
        btn_hesabıode = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_urunadı = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_toplam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_sepet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_masaıd = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        btn_gerı = new javax.swing.JButton();
        lbl_tarıh2 = new javax.swing.JLabel();
        lbl_kategorııcon = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_kategorıler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kategorılerİtemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_kategorıler, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 123, 499, -1));

        tbl_urunler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "URUNID", "ÜRÜNADI", "FİYAT", "KATEGORİ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_urunler);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 188, 700, 270));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ÜRÜN ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        txt_urunıd.setBackground(new java.awt.Color(0, 0, 0));
        txt_urunıd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_urunıd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_urunıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 160, 30));

        btn_satıs.setBackground(new java.awt.Color(0, 0, 0));
        btn_satıs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_satıs.setForeground(new java.awt.Color(255, 255, 255));
        btn_satıs.setText("ŞATIŞ");
        btn_satıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satısActionPerformed(evt);
            }
        });
        getContentPane().add(btn_satıs, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 160, 36));

        btn_hesabıode.setBackground(new java.awt.Color(0, 0, 0));
        btn_hesabıode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_hesabıode.setForeground(new java.awt.Color(255, 255, 255));
        btn_hesabıode.setText("HESABI ÖDE");
        btn_hesabıode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hesabıodeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hesabıode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ÜRÜN :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 80, 80, 40));

        lbl_urunadı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_urunadı.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_urunadı, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOPLAM :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 100, 40));

        lbl_toplam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_toplam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_toplam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 120, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SEPET :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 76, -1));

        lbl_sepet.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sepet.setText("alınan ürünler:");
        getContentPane().add(lbl_sepet, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 270, 550, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MASA NO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 29, -1, -1));

        lbl_masaıd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_masaıd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_masaıd.setText("jLabel5");
        getContentPane().add(lbl_masaıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 29, -1, -1));

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/ev.png"))); // NOI18N
        jButton19.setText(" ANAMENU");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 260, 180, 50));

        btn_gerı.setBackground(new java.awt.Color(0, 0, 0));
        btn_gerı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gerı.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerı.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/gozat.png"))); // NOI18N
        btn_gerı.setText("  GERİ");
        btn_gerı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerıActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gerı, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 330, 180, 50));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, 430, 60));

        lbl_kategorııcon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/javagri.png"))); // NOI18N
        lbl_kategorııcon.setText("jLabel5");
        lbl_kategorııcon.setMaximumSize(new java.awt.Dimension(128, 128));
        lbl_kategorııcon.setMinimumSize(new java.awt.Dimension(128, 128));
        getContentPane().add(lbl_kategorııcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 440, 280));

        arkaplan.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_kategorılerİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kategorılerİtemStateChanged
        dtm.setRowCount(0);
        int kategorıno = cmb_kategorıler.getSelectedIndex();
        if(kategorıno==0){
        lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/Coffee-icon.png")));
         lbl_kategorııcon.setText("SICAK İÇEÇEK ÇEŞİTLERİ");
        }
        else if(kategorıno==1){
            lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/Long-Island-Iced-Tea-icon.png")));
             lbl_kategorııcon.setText("SOĞUK İÇECEK ÇEŞİTLERİ");
        }
         else if(kategorıno==2){
             lbl_kategorııcon.setText("BURGER");
             lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/hamburger-icon.png")));
        }
         else if(kategorıno==3){
             lbl_kategorııcon.setText("KREP ÇEŞİTLERİ");
             lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/krep.jpg")));
        }
         else if(kategorıno==4){
              lbl_kategorııcon.setText("NARGİLE ÇEŞİTLERİ");
             lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/nargile.jpg")));
        }
         else if(kategorıno==5){
                        lbl_kategorııcon.setText("TATLILAR");
             lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/strawberry-cake-icon.png")));
        }
         else if(kategorıno==6){
            lbl_kategorııcon.setText("MAKARNA ÇEŞİTLERİ");
             lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/makarna.jpg")));
        }
         else if(kategorıno==7){
            lbl_kategorııcon.setText("PİZZA ÇEŞİTLERİ"); lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/pizza-icon.png")));
        }
         else{
           lbl_kategorııcon.setText("KATEGORİ ALGILANAMADI");    lbl_kategorııcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/asci.png")));
         }
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UKATEGORIID=" + kategorıno);
                while (rs.next()) {

                    int urunıd = rs.getInt("UID");
                    String urunısım = rs.getString("UISIM");
                    double fıyat = rs.getDouble("UFIAT");
                    int vergıoran = rs.getInt("UVERGIORAN");
                    String kategorıadı = rs.getString("UKATEGORI");
                    int kategorııd = rs.getInt("UKATEGORIID");
                    dtm.addRow(new Object[]{urunıd, urunısım, fıyat, vergıoran, kategorıadı, kategorııd});
                  
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }

    }//GEN-LAST:event_cmb_kategorılerİtemStateChanged

    private void btn_satısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satısActionPerformed
        String urunıd;
        urunıd = txt_urunıd.getText();
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UID=" + urunıd);
                if (rs.next()) {

                    topla = topla + rs.getDouble("UFIAT");
                    lbl_urunadı.setText("" + rs.getString("UISIM"));
                    sepet = sepet + " " + rs.getString("UISIM");
                    lbl_toplam.setText("" + topla);
                    txt_urunıd.setText("");
                    lbl_sepet.setText(sepet + "--");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ürün bulunamadı.");
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_satısActionPerformed

    public int bul(int a) {
        int yedek = a;
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM SA.RAPORLAR ");
            
            while (rs.next()) {
               
                    yedek++;
                
            }

        } catch (SQLException ex) {
            Logger.getLogger(satıs.class.getName()).log(Level.SEVERE, null, ex);
        }
        return yedek;
    }
    private void btn_hesabıodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hesabıodeActionPerformed
        try {
            int raporid = bul(1);
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM SA.RAPORLAR WHERE RID=" + raporid);

            if (rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Oooppss bir sorun var.");
                dispose();
                satıs nesne = new satıs(masaıd);
                nesne.setVisible(true);
                txt_urunıd.setText("");
                topla = 0;
                lbl_sepet.setText("");
                lbl_toplam.setText("");
                lbl_urunadı.setText("");
            } else {
              
                LocalTime now = LocalTime.now();
                LocalTime time = LocalTime.of(18, 20, 55);

                DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date tarih = new Date();
                System.out.println(format.format(tarih));
                String str = format.format(tarih);
                java.util.Date tarihJava = format.parse(str);
                System.out.println(str);
                String insert = "INSERT INTO SA.RAPORLAR (RID,RTUTAR,MASAID,RTARIH,RSAAT) VALUES ("
                        + raporid + "," + topla + ","
                        + masaıd + ",'" + str + "','"
                        + now.getHour() + ":" + now.getMinute()
                        + "')";
                System.out.println("" + insert);
                stmt.executeUpdate(insert);

                JOptionPane.showMessageDialog(rootPane, "Rapor eklendi.");
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(satıs.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void bnt_duzenleActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btn_hesabıodeActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        anamenu anamenü = new anamenu();
        anamenü.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btn_gerıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerıActionPerformed
        masalar nesne = new masalar();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_gerıActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(satıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(satıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(satıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(satıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new satıs(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton btn_gerı;
    private javax.swing.JButton btn_hesabıode;
    private javax.swing.JButton btn_satıs;
    private javax.swing.JComboBox<String> cmb_kategorıler;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_kategorııcon;
    private javax.swing.JLabel lbl_masaıd;
    private javax.swing.JLabel lbl_sepet;
    private javax.swing.JLabel lbl_tarıh2;
    private javax.swing.JLabel lbl_toplam;
    private javax.swing.JLabel lbl_urunadı;
    private javax.swing.JTable tbl_urunler;
    private javax.swing.JTextField txt_urunıd;
    // End of variables declaration//GEN-END:variables
}
