/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeotomasyonuprojesı;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casper
 */
public class urunekle extends javax.swing.JFrame {

    int ürünid;
    int kategoriid;
    String kategoriadi;
    DefaultTableModel dtm;

    public urunekle() {
        initComponents();
        SimpleDateFormat bicim = new SimpleDateFormat("dd/M/yyyy");
        Date tarih = new Date();

        lbl_tarıh2.setText((bicim.format(tarih)));
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"UID", "UISIM", "UFIAT", "UVERGIORAN", "UKATEGORI", "UKATEGORIID"});
        tbl_urunler.setModel(dtm);
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.KATEGORILER ");
                while (rs.next()) {
                    int kategorııd = rs.getInt("UKATEGORIID");
                    String kategorıadı = rs.getString("UKATEGORI");
                    cmb_kategorıler.addItem(kategorıadı);

                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_urunıd = new javax.swing.JTextField();
        txt_urunadı = new javax.swing.JTextField();
        txt_urunfıyat = new javax.swing.JTextField();
        txt_urunvergı = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_anamenu = new javax.swing.JButton();
        btn_gerı = new javax.swing.JButton();
        btn_urunekle = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lbl_tarıh2 = new javax.swing.JLabel();
        cmb_kategorıler = new javax.swing.JComboBox<>();
        rb_sıcakıcecek = new javax.swing.JRadioButton();
        rb_nargile = new javax.swing.JRadioButton();
        rb_sogukıcecek = new javax.swing.JRadioButton();
        rb_burger = new javax.swing.JRadioButton();
        rb_tatlılar = new javax.swing.JRadioButton();
        rb_krep = new javax.swing.JRadioButton();
        rb_makarna = new javax.swing.JRadioButton();
        rb_pizza = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_urunler = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_urunıd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 77, 210, 22));
        getContentPane().add(txt_urunadı, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 127, 210, 22));
        getContentPane().add(txt_urunfıyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));
        getContentPane().add(txt_urunvergı, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 227, 210, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ÜRÜN ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 74, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ÜRÜN ADI :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 124, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FİYATI :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 176, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VERGİ :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 223, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KATEGORİ :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 274, -1, -1));

        btn_anamenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_anamenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/ev.png"))); // NOI18N
        btn_anamenu.setText(" ANAMENU");
        btn_anamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anamenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        btn_gerı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gerı.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/gozat.png"))); // NOI18N
        btn_gerı.setText("  GERİ");
        btn_gerı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerıActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gerı, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 149, -1));

        btn_urunekle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_urunekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/urun_ekle.png"))); // NOI18N
        btn_urunekle.setText(" EKLE");
        btn_urunekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_urunekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/urun_duzenle.png"))); // NOI18N
        jButton12.setText(" DÜZENLE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        lbl_tarıh2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tarıh2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarıh2.setText("jLabel1");
        getContentPane().add(lbl_tarıh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, 430, 60));

        cmb_kategorıler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kategorılerİtemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_kategorıler, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 930, 40));

        rb_sıcakıcecek.setForeground(new java.awt.Color(255, 255, 255));
        rb_sıcakıcecek.setText("SICAK İÇECEKLER");
        rb_sıcakıcecek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_sıcakıcecekActionPerformed(evt);
            }
        });
        getContentPane().add(rb_sıcakıcecek, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        rb_nargile.setForeground(new java.awt.Color(255, 255, 255));
        rb_nargile.setText("NARGİLE");
        rb_nargile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nargileActionPerformed(evt);
            }
        });
        getContentPane().add(rb_nargile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, -1));

        rb_sogukıcecek.setForeground(new java.awt.Color(255, 255, 255));
        rb_sogukıcecek.setText("SOĞUK İÇECEKELR");
        rb_sogukıcecek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_sogukıcecekActionPerformed(evt);
            }
        });
        getContentPane().add(rb_sogukıcecek, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        rb_burger.setForeground(new java.awt.Color(255, 255, 255));
        rb_burger.setText("BURGER");
        rb_burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_burgerActionPerformed(evt);
            }
        });
        getContentPane().add(rb_burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, -1));

        rb_tatlılar.setForeground(new java.awt.Color(255, 255, 255));
        rb_tatlılar.setText("TATLILAR");
        rb_tatlılar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_tatlılarActionPerformed(evt);
            }
        });
        getContentPane().add(rb_tatlılar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 110, -1));

        rb_krep.setForeground(new java.awt.Color(255, 255, 255));
        rb_krep.setText("KREP");
        rb_krep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_krepActionPerformed(evt);
            }
        });
        getContentPane().add(rb_krep, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 360, 110, -1));

        rb_makarna.setForeground(new java.awt.Color(255, 255, 255));
        rb_makarna.setText("MAKARNA");
        rb_makarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_makarnaActionPerformed(evt);
            }
        });
        getContentPane().add(rb_makarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 110, -1));

        rb_pizza.setForeground(new java.awt.Color(255, 255, 255));
        rb_pizza.setText("PİZZA");
        rb_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(rb_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 400, 110, -1));

        tbl_urunler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "URUNID", "ÜRÜNADI", "FİYAT", "KATEGORİ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_urunler);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 930, 310));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("* ÜRÜN GÜNCELLEŞTİRMESİ DIŞINDA YAPACAGINIZ İD GİRİŞİ GEÇERSİZ KILINIR. ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 460, 20));

        arkaplan.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        arkaplan.setForeground(new java.awt.Color(255, 255, 255));
        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeotomasyonuprojesı/Yeni klasör/images/maxresdefault-3.jpg"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_urunekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunekleActionPerformed
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UKATEGORIID=" + kategoriid);
                if (rs.next()) {
                    ürünid = rs.getInt("UID");
                    while (rs.next()) {
                        ürünid = rs.getInt("UID");
                    }
                    ürünid++;
                } else {
                    String den = kategoriid + "01";
                    ürünid = Integer.parseInt(den);
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UID=" + ürünid);
                if (rs.next()) {

                    JOptionPane.showMessageDialog(rootPane, "EKLEME İŞLEMİNDE LÜTFEN İD ALANINI BOS BIRAKINIZ.");
                    txt_urunıd.setText("");
                    txt_urunadı.setText("");
                    txt_urunfıyat.setText("");

                    txt_urunvergı.setText("");
                } else {
                    String insert = "INSERT INTO SA.URUNLER (UID,UISIM,UFIAT,UVERGIORAN,UKATEGORI,UKATEGORIID) VALUES ("
                            + ürünid + ",'" + txt_urunadı.getText().trim()
                            + "'," + txt_urunfıyat.getText().trim() + ","
                            + txt_urunvergı.getText().trim() + ",'"
                            + kategoriadi + "',"
                            + kategoriid
                            + ")";
                    System.out.println("İNSERT" + insert);
                    stmt.executeUpdate(insert);
                    urunekle nesne = new urunekle();
                    nesne.setVisible(true);
                    dispose();
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }


    }//GEN-LAST:event_btn_urunekleActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (txt_urunıd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ürün id numarası giriniz.");
            txt_urunıd.setText("");
            txt_urunadı.setText("");
            txt_urunfıyat.setText("");
            // txt_urunkategori.setText("");
            // txt_urunkategorııd.setText("");
            txt_urunvergı.setText("");
            return;
        } else {
            int gelenbarkod = Integer.parseInt(txt_urunıd.getText());
            try {
                try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UID=" + gelenbarkod);
                    if (rs.next()) {
                        String update = "UPDATE URUNLER SET UID=" + txt_urunıd.getText().trim()
                                + ",UISIM='" + txt_urunadı.getText().trim()
                                + "',UFIAT=" + txt_urunfıyat.getText().trim()
                                + "WHERE UID=" + txt_urunıd.getText().trim();
                        System.out.println("update" + update);
                        stmt.executeUpdate(update);
                        urunekle nesne = new urunekle();
                        nesne.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Girdiğiniz ürün bulunamadı.");
                    }
                    con.close();
                }
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
        }
     
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn_anamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anamenuActionPerformed
        anamenu nesne = new anamenu();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_anamenuActionPerformed

    private void btn_gerıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerıActionPerformed
        ürünler nesne = new ürünler();
        nesne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_gerıActionPerformed

    private void cmb_kategorılerİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kategorılerİtemStateChanged
        dtm.setRowCount(0);
        int kategorıno = cmb_kategorıler.getSelectedIndex();
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/abc ", "sa", "as")) {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM SA.URUNLER WHERE UKATEGORIID=" + kategorıno);
                while (rs.next()) {

                    int urunıd = rs.getInt("UID");
                    String urunısım = rs.getString("UISIM");
                    double fıyat = rs.getDouble("UFIAT");
                    int vergıoran = rs.getInt("UVERGIORAN");
                    String kategorıadı = rs.getString("UKATEGORI");
                    int kategorııd = rs.getInt("UKATEGORIID");
                    dtm.addRow(new Object[]{urunıd, urunısım, fıyat, vergıoran, kategorıadı, kategorııd});
                    //    System.out.println("kategorı no : "+kategorıno);
                }
                con.close();
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_cmb_kategorılerİtemStateChanged

    private void rb_burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_burgerActionPerformed
        if (rb_burger.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 2;
            kategoriadi = "BURGER";
        }
    }//GEN-LAST:event_rb_burgerActionPerformed

    private void rb_nargileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nargileActionPerformed
        if (rb_nargile.isSelected()) {
            rb_burger.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 4;
            kategoriadi = "NARGİLE";

        }
    }//GEN-LAST:event_rb_nargileActionPerformed

    private void rb_tatlılarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_tatlılarActionPerformed
        if (rb_tatlılar.isSelected()) {
            rb_nargile.setSelected(false);
            rb_burger.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 5;
            kategoriadi = "TATLILAR";

        }
    }//GEN-LAST:event_rb_tatlılarActionPerformed

    private void rb_makarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_makarnaActionPerformed
        if (rb_makarna.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_burger.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 6;
            kategoriadi = "MAKARNA";
        }
    }//GEN-LAST:event_rb_makarnaActionPerformed

    private void rb_sogukıcecekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_sogukıcecekActionPerformed
        if (rb_sogukıcecek.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_burger.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 1;
            kategoriadi = "SOGUKİCECEKLER";
        }
    }//GEN-LAST:event_rb_sogukıcecekActionPerformed

    private void rb_sıcakıcecekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_sıcakıcecekActionPerformed
        if (rb_sıcakıcecek.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_burger.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 0;
            kategoriadi = "SICAKİCECEKLER";
        }
    }//GEN-LAST:event_rb_sıcakıcecekActionPerformed

    private void rb_krepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_krepActionPerformed
        if (rb_krep.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_pizza.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_burger.setSelected(false);
            kategoriid = 3;
            kategoriadi = "KREP";
        }
    }//GEN-LAST:event_rb_krepActionPerformed

    private void rb_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_pizzaActionPerformed
        if (rb_pizza.isSelected()) {
            rb_nargile.setSelected(false);
            rb_tatlılar.setSelected(false);
            rb_burger.setSelected(false);
            rb_makarna.setSelected(false);
            rb_sogukıcecek.setSelected(false);
            rb_sıcakıcecek.setSelected(false);
            rb_krep.setSelected(false);
            kategoriid = 7;
            kategoriadi = "PİZZA";
        }
    }//GEN-LAST:event_rb_pizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urunekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urunekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urunekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urunekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urunekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton btn_anamenu;
    private javax.swing.JButton btn_gerı;
    private javax.swing.JButton btn_urunekle;
    private javax.swing.JComboBox<String> cmb_kategorıler;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_tarıh2;
    private javax.swing.JRadioButton rb_burger;
    private javax.swing.JRadioButton rb_krep;
    private javax.swing.JRadioButton rb_makarna;
    private javax.swing.JRadioButton rb_nargile;
    private javax.swing.JRadioButton rb_pizza;
    private javax.swing.JRadioButton rb_sogukıcecek;
    private javax.swing.JRadioButton rb_sıcakıcecek;
    private javax.swing.JRadioButton rb_tatlılar;
    private javax.swing.JTable tbl_urunler;
    private javax.swing.JTextField txt_urunadı;
    private javax.swing.JTextField txt_urunfıyat;
    private javax.swing.JTextField txt_urunvergı;
    private javax.swing.JTextField txt_urunıd;
    // End of variables declaration//GEN-END:variables
}
